# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

resources:
  - repo: self

stages:
  - stage: Provision #terraform
    displayName: 'Terraforming on Azure..'
    #dependsOn: Build
    jobs:
    - job: Provision  
      displayName: 'Provisioning Container Instances'
      pool:
        vmImage: ubuntu-latest
      variables:
      - group: TerraformEnvVars
      steps: #input script, what you would write in cmd
        - script: | 
            set -e
            terraform init -input=false 
            terraform apply -input=false -auto-approve
          name: 'RunTerraform'
          displayName: 'Run Terraform'
          env:
            ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
            # might need more env vars
            # they are from pipeline library
            # they are passed to terraform
          #tfstate and backup file can be stored in azure instead. not a must. 


